import { ImageManager } from 'easy-email-core';

const defaultImagesMap = {
  IMAGE_08:
    'about:blank',
  IMAGE_09:
    'about:blank',
  IMAGE_10:
    'about:blank',
  IMAGE_11:
    'about:blank',
  IMAGE_12:
    'about:blank',
  IMAGE_13:
    'about:blank',
  IMAGE_14:
    'about:blank',
  IMAGE_15:
    'about:blank',
  IMAGE_16:
    'about:blank',
  IMAGE_17:
    'about:blank',
  IMAGE_18:
    'about:blank',
  IMAGE_19:
    'about:blank',
  IMAGE_20:
    'about:blank',
  IMAGE_21:
    'about:blank',
  IMAGE_22:
    'about:blank',
  IMAGE_23:
    'about:blank',
  IMAGE_24:
    'about:blank',
  IMAGE_25:
    'about:blank',
  IMAGE_26:
    'about:blank',
  IMAGE_27:
    'about:blank',
  IMAGE_28:
    'about:blank',
  IMAGE_29:
    'about:blank',
  IMAGE_30:
    'about:blank',
  IMAGE_31:
    'about:blank',
  IMAGE_32:
    'about:blank',
  IMAGE_33:
    'about:blank',
  IMAGE_34:
    'about:blank',
  IMAGE_35:
    'about:blank',
  IMAGE_36:
    'about:blank',
  IMAGE_37:
    'about:blank',
  IMAGE_38:
    'about:blank',
  IMAGE_39:
    'about:blank',
  IMAGE_40:
    'about:blank',
  IMAGE_41:
    'about:blank',
  IMAGE_42:
    'about:blank',
  IMAGE_43:
    'about:blank',
  IMAGE_44:
    'about:blank',
  IMAGE_45:
    'about:blank',
  IMAGE_46:
    'about:blank',
  IMAGE_47:
    'about:blank',
  IMAGE_48:
    'about:blank',
  IMAGE_49:
    'about:blank',
  IMAGE_50:
    'about:blank',
  IMAGE_51:
    'about:blank',
  IMAGE_52:
    'about:blank',
  IMAGE_53:
    'about:blank',
  IMAGE_54:
    'about:blank',
  IMAGE_55:
    'about:blank',
  IMAGE_56:
    'about:blank',
  IMAGE_57:
    'about:blank',
  IMAGE_58:
    'about:blank',
  IMAGE_59:
    'about:blank',
  IMAGE_60:
    'about:blank',
  IMAGE_61:
    'about:blank',
  IMAGE_62:
    'about:blank',
  IMAGE_63:
    'about:blank',
  IMAGE_64:
    'about:blank',
  IMAGE_65:
    'about:blank',
  IMAGE_66:
    'about:blank',
  IMAGE_67:
    'about:blank',
  IMAGE_68:
    'about:blank',
  IMAGE_69:
    'about:blank',
  IMAGE_70:
    'about:blank',
  IMAGE_71:
    'about:blank',
};

ImageManager.add(defaultImagesMap);

export function getImg(name: keyof typeof defaultImagesMap) {
  return ImageManager.get(name);
}
